theme: minima
title: "CERTREQ blog"
tagline: "CERTREQ the quest for certificates"
author: "Daniel Westfall"
description: "Daniel Westfall's documented journey to the CPACC and WAS certificates"
language: en

footer_links:
  - text: "CERTREQ Home"
    url: "https://certreq.dev/"
  - text: "CERTREQ Link 1"
    url: "https://certreq.dev/"
  - text: "CERTREQ Link 2"
    url: "https://certreq.dev/"
